import time as _tm
#import logerfc as _lfc

#import binHastingsLib1uu as _bHL
import binHastingsLibSwU as _bHL
#import binHastingsLibSwUc as _bHL
#  Given data generated by binomial distribution with parameter
#  (p, n), fit this, and try to find (p, n)

######
burn = 1000
NMC  = 1000
pT = 1-0.05
nT = 10
N  = 500

#  create data
#cts = _N.random.binomial(nT, pT, size=N)
cts = _N.random.negative_binomial(nT, pT, size=N)
mL      = 20000
pcdlog  = _N.empty(mL)        #precomputed logs
pcdlog[1:mL] = _N.log(_N.arange(1, mL))

t1 = _tm.time()
rns  = _N.empty(burn + NMC)
us   = _N.empty(burn + NMC)

_bHL.MCMC(burn, NMC, cts, rns, us, 1, pcdlog)
t2 = _tm.time()
print (t2-t1)

ps = 1 / (1 + _N.exp(-us))

fig=_plt.figure(figsize=(2*5, 2*4))
fig.add_subplot(2, 2, 1)
_plt.plot(ps)
fig.add_subplot(2, 2, 2)
_plt.plot(rns)
fig.add_subplot(2, 2, 3)
_plt.hist(ps, bins=_N.linspace(0, 1, 101))
fig.add_subplot(2, 2, 4)
_plt.hist(rns, bins=_N.linspace(0, 300, 301))
